#+TITLE: 技术笔记
#+STARTUP: indent

* Table of Contents :TOC_2_gh:noexport:
- [[#cc-笔记][C&C++ 笔记]]
  - [[#基本概念][基本概念]]
  - [[#lambda-语法2018-08-28-二][lambda 语法（<2018-08-28 二>）]]
  - [[#stdvector-2018-08-28-二][std::vector (<2018-08-28 二>)]]
  - [[#timermicro-second-2018-09-04-二][Timer(micro-second) (<2018-09-04 二>)]]
  - [[#matrix-libraries][Matrix Libraries]]
- [[#data-structure-and-algorithm][Data structure and Algorithm]]
  - [[#graph-data-structure-2018-08-28-二][Graph data structure (<2018-08-28 二>)]]
  - [[#最短路径算法][最短路径算法]]
  - [[#用数组实现邻接表][用数组实现邻接表]]
  - [[#快速排序算法][快速排序算法]]
  - [[#子符串匹配算法-2018-08-31-五][子符串匹配算法 (<2018-08-31 五>)]]
- [[#software-tips][Software Tips]]
  - [[#spacemacs-2018-08-28-二][spacemacs (<2018-08-28 二>)]]
  - [[#cmake-2018-08-31-五][CMake (<2018-08-31 五>)]]
  - [[#git-2018-09-01-六][Git (<2018-09-01 六>)]]
  - [[#tig-2018-09-06-四][tig (<2018-09-06 四>)]]
  - [[#ubuntu-2018-09-04-二][Ubuntu (<2018-09-04 二>)]]
  - [[#cygwin][Cygwin]]
  - [[#vim][Vim]]
- [[#java][Java]]
- [[#windows][windows]]
  - [[#终端][终端]]

* C&C++ 笔记
** 基本概念
- |= 是按位或并赋值的意思，a|=b就是a=a|b
- clang-tidy is a clang-based C++ “linter” tool
** lambda 语法（<2018-08-28 二>）
  #+BEGIN_SRC C++
  [captures] (parameter list) -> return-type
  {
    lambda body;
  }
  #+END_SRC
  其中 captures 中要么按值获取，要么按引用获取。
  If you reference capture a const local variable, it becomes a const reference in the lambda.

** std::vector (<2018-08-28 二>)
- vector.capacity() 表示容量大小，占用多少内存
- vector.size() 表示元素大小，占用实际内存
- vector.max_size() 最大容量
- 当前 v.capacity()=c,v.size()=s;如果 s=c+1，那么 c 就会加倍

** Timer(micro-second) (<2018-09-04 二>)
#+BEGIN_SRC c++
double startTimeInMicroSec;                 // starting time in micro-second
double endTimeInMicroSec;                         // ending time in micro-second
int stopped;                                      // stop flag
#if defined(WIN32) || defined(_WIN32)
  LARGE_INTEGER frequency;   // ticks per second
  LARGE_INTEGER startCount;  //
  LARGE_INTEGER endCount;    //
#else
  timeval startCount;  //
  timeval endCount;    //
#endif
void start()
{
  #if defined(WIN32) || defined(_WIN32)
    QueryPerformanceCounter(&startCount);
  #else
    gettimeofday(&startCount, NULL);
  #endif
}
void end()
{
  #if defined(WIN32) || defined(_WIN32)
    QueryPerformanceCounter(&endCount);
  #else
    gettimeofday(&endCount, NULL);
  #endif
}
double getElapsedTimeInMicroSec()
{
  #if defined(WIN32) || defined(_WIN32)
  startTimeInMicroSec = startCount.QuadPart * (1000000.0 / frequency.QuadPart);
  endTimeInMicroSec = endCount.QuadPart * (1000000.0 / frequency.QuadPart);
  #else
  startTimeInMicroSec = (startCount.tv_sec * 1000000.0) + startCount.tv_usec;
  endTimeInMicroSec = (endCount.tv_sec * 1000000.0) + endCount.tv_usec;
  #endif
  return endTimeInMicroSec - startTimeInMicroSec;
}
#+END_SRC

** Matrix Libraries
*** Eigen
只有头文件，使用方便，支持的矩阵运算也非常丰富
*** Armadillo
C++下 Matlab 替代品，Matlab 的矩阵操作函数都可以找到对应

* Data structure and Algorithm
** Graph data structure (<2018-08-28 二>)
*** 图其实就是一个链表，其节点和边的数据结构定义如下
    #+BEGIN_SRC C++
    typedef struct _LINE
    {
      int end;
      int weight;
      struct _LINE* next;
    }LINE;

    typedef struct _VECTEX
    {
      int start;
      int number;
      LINE* neighbor;
      struct _VECTEX* next;
    }VECTEX;

    typedef struct _GRAPH
    {
      int count;
      VECTEX* head;
    }GRAPH;
    #+END_SRC

** 最短路径算法
*** Floyd-Warshall
    #+BEGIN_SRC C++
    for(k=1;k<=n;k++)
       for(i=1;i<=n;i++)
          for(j=1;j<=n;j++)
            if(e[i][k]<inf && e[k][j]<inf && e[i][j]>e[i][k]+e[k][j])
                e[i][j]=e[i][k]+e[k][j];
    #+END_SRC

*** Dijkstra
    #+BEGIN_SRC C++ -N
    for(i=1;i<=n-1;i++)
    {
      // 找到离1号顶点最近的顶点
      min = inf;
      for (j = 1; j <= n; j++)
      {
        if (book[j] == 0 && dis[j] < min)
        {
          min = dis[j];
          u = j;
        }
      }
      book[u] = 1;
      for (v = 1; v <= n; v++)
      {
        if (e[u][v] < inf)
        {
          if (dis[v] > dis[u] + e[u][v])
            dis[v] = dis[u] + e[u][v];
        }
      }
    }
    #+END_SRC

** 用数组实现邻接表
分别使用 u,v,w,first,next 五个数组保存图的信息,u、v 和 w 三个数组用来记录每条边的具体信息，
即 u[i]、v[i]和 w[i]表示 第 i 条边是从第 u[i]号顶点到 v[i]号顶点（u[i]->v[i]），且权值为 w[i]
first[j]的值代表第 j 号顶点所在的其中一条边的编号，next[k]表示第 k 条边连接着第 next[k]条边，且它
们属于同一个顶点，即在 next 数组中可以递归找到同一个顶点的所有边.
** 快速排序算法
核心代码
#+BEGIN_SRC C++
void QuickSort(std::vector<T>& data, int s, int e)
{
  if (s >= e)
    return;

  T center = data[s];
  int i = s;
  int j = e;
  while (1)
  {
    while (data[j] >= center && i < j)
    {
      j--;
    }
    while (data[i] <= center && i < j)
    {
      i++;
    }
    if (i < j)
    {
      T temp = data[j];
      data[j] = data[i];
      data[i] = temp;
    }
    else
    {
      data[s] = data[i];
      data[i] = center;
      break;
    }
  }
  QuickSort<int>(data, s, i - 1);
  QuickSort<int>(data, j + 1, e);
}
#+END_SRC

** 子符串匹配算法 (<2018-08-31 五>)
*** KMP
*** BM
*** Sunday
核心代码
#+BEGIN_SRC C++
int sunday(const string& tar, const string& src)
{
  int idx = 0;
  size_t len_src = src.length();
  while (idx + len_src <= tar.length())
  {
    for (size_t i = 0; i < len_src; ++i)
    {
      if (src[i] != tar[idx + i])
        break;
      if (i == len_src - 1)
        return idx;
    }
    for (size_t i = 0; i < len_src; ++i)
    {
      if (src[i] == tar[idx + len_src])
      {
        idx += len_src - i;
        break;
      }
      if (i == len_src - 1)
      {
        idx += len_src + 1;
      }
    }
  }
  return -1;
}
#+END_SRC

* Software Tips
** spacemacs (<2018-08-28 二>)
*** 按键说明
 1) 功能键
    + C-  意思是按住  Ctrol 键
    + M-   意指  Meta 键 (键盘上若无  Meta 键，则可以  ALT ESC 键来取而代之)
    + DEL  意指退格键 (不是 删除( Delete) key)
    + RET  意指回车键
    + SPC  意指空格键
    + ESC  意指  Escape 键
    + TAB  意指  Tab 键
    + 像 "C-M-" (or "M-C") 这样连在一起的意味着同时按住  Control 和  Meta
*** 查看变量的命令
- 查看变量的值（c-h v），快捷键对应的函数(c-h k)，方便查找函数(c-h f)
*** ORG快捷键
1) Input(org-insert-structure-template)
   + s    #+begin_src ... #+end_src
2) 功能键
   + C-  意思是按住 Ctrol 键
   + M-   意指 Meta 键 (键盘上若无 Meta 键，则可以 ALT ESC 键来取而代之)
   + DEL  意指退格键 (不是 删除(Delete) key)
   + RET  意指回车键
   + SPC  意指空格键
   + ESC  意指 Escape 键
   + TAB  意指 Tab 键
   + 像 "C-M-" (or "M-C") 这样连在一起的意味着同时按住 Control 和 Meta 
 
*** ORG 
1) Input
   + s    #+begin_src ... #+end_src 
   + e    #+begin_example ... #+end_example  : 单行的例子以冒号开头
   + q    #+begin_quote ... #+end_quote      通常用于引用，与默认格式相比左右都会留出缩进
   + v    #+begin_verse ... #+end_verse      默认内容不换行，需要留出空行才能换行
   + c    #+begin_center ... #+end_center
   + l    #+begin_latex ... #+end_latex
   + L    #+latex:
   + h    #+begin_html ... #+end_html
   + H    #+html:
   + a    #+begin_ascii ... #+end_ascii
   + A    #+ascii:
   + i    #+index: line
   + I    #+include: line
   上面的单字母为快捷键字母，如输入一个< s 然后  TAB 后就变为"#+BEGIN_SRC #+END_SRC"，也就是命令  org-insert-structure-template
2) Move
   + gh  outline-up-heading
   + gj  org-forward-heading-same-level
   + gl  outline-next-visible-heading
   + gk  org-backward-heading-same-level
   + M-l	org-metaright
   + M-h	org-metaleft
   + M-k	org-metaup
   + M-j	org-metadown

*** org 中英文对齐
首先设中文字体，添加如下配置
#+begin_src elisp
;;单独设置中文字体，解决有中文是卡顿现象
(dolist (charset '(kana han cjk-misc bopomofo))
  (set-fontset-font (frame-parameter nil 'font) charset
                    (font-spec :family "微软雅黑" :size 16)))
#+end_src
然后使用  SPC z x 来调整字体大小，发现  org-table 里对齐为此
*** org 输入特殊字符
- 输入下划线用  underlined\under == underlined_
- 输入加号用 \plus{}< == +<
- 输入周长公式 \pi{}d
- 中文和英文之间多了空格，可能是因为pangu-space-mode的原因，关掉它就可以了。主要是因为安装了chinese这个layer，把它删除
*** org-mode自动换行
参考：https://emacs-china.org/t/emacs-org-mode/6748/4
关于auto-fill mode:
用 M-x auto-fill-mode 打开 auto-fill mode；
用 M-q 重排段落的每行字数；
用 C-u 80 C-x f 设定每行80字，再在需要重排的地方按 M-q 更新。

关于org的自动缩进：
org确实会在一些地方默认进行缩进，例如代码块。
如果打开了 org-indent-mode 也是会按照大纲逐级缩进。
Emacs的自动缩进也有可能造成你说的现象，检查一下 electric-indent-mode， newline-and-indent 之类的设置。

关于日志换行的选择：
对于写日志这种会频繁出现长段落的情况，除了用 auto-fill mode 进行 hard linewrap （是翻译成硬换行吗），还可以用soft linewrap的方案 （根据窗口大小自动调整每行显示的字数）。
我记得，如果有 setq truncate-lines nil ， org就自动显示换行了，做到soft linewrap的效果。
当然，Emacs有更友好的 visual-line-mode ，是写英语论文的必备。
*** clang-format-region
With this integration you can press the bound key and clang-format
will format the current line in NORMAL and INSERT mode or the selected
region in VISUAL mode. The line or region is extended to the next bigger syntactic entity.
*** helm-projectile
- (setq projectile-indexing-method 'native)
- (spacemacs/set-leader-keys "pf" 'counsel-projectile-find-file)
- 在查找文件时直接输入' C:/'，可以直接切换磁盘目录
*** org 文件内添加目录（内部链接）
直接在目录的地方输入: TOC:或者: TOC_2_gh:或者: TOC_2_gh:noexport:
[[https://github.com/snosov1/toc-org][org-toc]]
*** dired-mode
- SPC f j 进入dired模式，其实是打开dired buffer
- M-x dired 选中一个文件夹再回车，进入dired
- 快捷命令
| 命令    | 作用                                  |
|---------+---------------------------------------|
| +       | 新建一个目录                          |
| C-x C-f | 新建一个文件                          |
| j,k,n,p | 上下移动                              |
| <,>     | 目录行中移动                          |
| ^       | 上一级目录                            |
| g       | 刷新文件列表                          |
| m       | 标记文件或目录（*标）                 |
| d       | flag(D标）                            |
| u       | 取消标记                              |
| x       | 删除D标文件                           |
| D       | 删除*标文件，也可以直接删除文件或目录 |
| C       | 拷贝到...                             |
| R       | 重命名...，移动到...                  |
| w       | 复制文件名                            |
| v       | 预览文件，q退出预览                   |

*** doom-modeline
这个  modeline 依赖  all-the-icons 里的字体，从a ll-the-icons 仓库  clone 下来，windows 要手动安装。其它可以在  emacs 里直接使用  all-the-icons-font-install 安装.
*** 按键映射
#+BEGIN_SRC elisp
(define-key evil-insert-state-map (kbd "C-h") (kbd "<left>"))
(define-key evil-insert-state-map (kbd "C-j") (kbd "<down>"))
(define-key evil-insert-state-map (kbd "C-k") (kbd "<up>"))
(define-key evil-insert-state-map (kbd "C-l") (kbd "<right>"))
#+END_SRC
*** 一些配置
- (setq vc-handled-backends ())
- (setq vc-handled-backends nil)
- (setq create-lockfiles nil) 禁止创建锁定文件
*** 国内源
- 腾讯源 https://mirrors.cloud.tencent.com/help/elpa.html
** CMake (<2018-08-31 五>)
*** 获取路径
+ ${PROJECT_SOURCE_DIR}
+ ${CMAKE_CURRENT_SOURCE_DIR}
*** 编译指令
 cmake -G "MSYS Makefiles" ..
** Git (<2018-09-01 六>)
*** 配置
**** git config --global push.default simple
这个配置可以让 GIT 在 PUSH 时，只 PUSH 当前的分支
**** git config --global diff.submodule log
**** git config status.submodulesummary 1
**** core.autocrlf
#提交时转换为LF，检出时转换为CRLF
git config --global core.autocrlf true
#提交时转换为LF，检出时不转换
git config --global core.autocrlf input
#提交检出均不转换
git config --global core.autocrlf false
**** core.safecrlf
#拒绝提交包含混合换行符的文件
git config --global core.safecrlf true
#允许提交包含混合换行符的文件
git config --global core.safecrlf false
#提交包含混合换行符的文件时给出警告
git config --global core.safecrlf warn
*** submodule
**** git submodule add url
**** git submodule sync
**** git submodule init
**** git submodule update
*** 本地  reset后，造成与远程不同步时处理办法
 git pull --rebase origin master
解决冲突再
 git rebase --continue
*** 修改历史提交的commit信息
- git rebase -i HEAD~3
- 修改pick为edit，保存退出
- git commit --amend
- git rebase --continue
** tig (<2018-09-06 四>)
*** keymap
- [shift + c] switch to corresponding branch
** Ubuntu (<2018-09-04 二>)
*** U 盘 read-only
1) 方法一
#+BEGIN_SRC shell
sudo mount -o remount,rw /dev/sdc
#+END_SRC
2) 方法二
#+BEGIN_SRC shell
sudo umount
sudo dosfsck -a /dev/sdc
#+END_SRC
<<<<<<< HEAD
** Cygwin
*** 安装  gcc/g++编译环境
- cmake
- make
- binutils
- gcc-g++
- mingw-86_64-gcc-g++
- gdb
- gcc-g++-core
*** 指定anaconda路径
export PATH=/cygdrive/c/ProgramData/Anaconda3:$PATH #注意要使用cygdrive/c/来指定磁盘
** Vim
*** vim做映射时使用<C-u>做前缀的原因
其实<C-U>的作用就是在command模式中删除所有的文本
*** NERD_commenter
- ,ca在可选的注释方式之间切换，比如C/C++ 的块注释/* */和行注释//
- ,cc注释当前行
- ,c<space> 切换注释/非注释状态
- ,cs 以”性感”的方式注释
- ,cA 在当前行尾添加注释符，并进入Insert模式
- ,cu 取消注释
- ,c$ 从光标开始到行尾注释  ，这个要说说因为c$也是从光标到行尾的快捷键，这个按过逗号（，）要快一点按c$
- 2,cc 光标以下count行添加注释
- 2,cu 光标以下count行取消注释
- 2,cm:光标以下count行添加块注释(2,cm)
- Normal模式下，几乎所有命令前面都可以指定行数
- Visual模式下执行命令，会对选中的特定区块进行注释/反注释
* Java
-  Java的 == 运算符比较的是对象（不是基本类型）的引用，而不是对象的值

*** 将 CapsLock 设为 Ctrl
#+BEGIN_SRC shell
vim /etc/default/keyboard
add XKBOPTIONS="ctrl:swapcaps" or XKBOPTIONS="ctrl:nocaps"
run sudo dpkg-reconfigure keyboard-configuration
#+END_SRC

*** 安装emacs26.2
- sudo add-apt-repository ppa:kelleyk/emacs
- sudo apt update
- sudo apt install emacs26
* windows
** 终端
先安装了 cygwin
再安装一系列插件：git tig zsh fish 
安装 oh-my-zsh
oh-my-zsh 的插件:zsh-syntax... zsh-suggestion... (bug：直接在 github 上用右键下载，win10 不能识别，要下载全部的库)
oh-my-zsh 的主题，特殊符号不能显示-->又去解决字体问题，下载 nerd 字体，最后从自己电脑复制过去的
在 cygwin 的 minsys 中，中文显示乱码，git 使用也异常（可能是原先 git for windows 中 git 版本与 cygwin 中的 git 版本不兼容造成）
想在 git for windows 的 minsys 中直接使用 cygwin 中的 tmux,zsh，但一直不能识别，不知是不是系统环境变量 PATH 没起作用？
尝试过把 tmux 的文件和依赖直接复制过去，并不行。
把 git for windows 中的 bash,minsys 复制到 cygwin 中，并不能直接运行
zsh 中 git log 显示中文乱码，在 zshrc 中设置 export LESSCHARSET=UTF-8
另一个 windows 体验 linux 的工具 babun, 准备尝试
